# This is a preferences file for the bacon tool
# https://dystroy.org/bacon/config/

summary = true
wrap = true
reverse = false
help_line = false

default_job = "clippy-pedantic"

env.CARGO_TERM_COLOR = "always"

[keybindings]
ctrl-c = "quit"
ctrl-q = "quit"
q = "quit"
Esc = "back"
Home = "scroll-to-top"
End = "scroll-to-bottom"
Up = "scroll-lines(-1)"
Down = "scroll-lines(1)"
PageUp = "scroll-page(-1)"
PageDown = "scroll-page(1)"
F5 = "refresh"
Space = "refresh"
ctrl-r = "toggle-raw-output"
ctrl-b = "toggle-backtrace"
ctrl-s = "toggle-summary"
ctrl-w = "toggle-wrap"

i = "job:initial"
c = "job:check"
l = "job:clippy"
p = "job:clippy-pedantic"
f = "job:format"
x = "job:fix"
d = "job:doc-open"
t = "job:test"
r = "job:run"


[jobs.check]
command = ["cargo", "check", "--all-features", "--all-targets"]

[jobs.clippy]
command = [
    "cargo", "clippy", "--all-features", "--all-targets",
    "--",
    "--warn", "clippy::panic",
    "--warn", "clippy::unwrap_used",
    "--warn", "clippy::unwrap_in_result",
    "--allow", "clippy::missing_errors_doc",
]

[jobs.clippy-plain]
command = ["cargo", "clippy", "--all-features", "--all-targets"]

[jobs.clippy-pedantic]
command = [
    "cargo", "clippy", "--all-features", "--all-targets",
    "--",
    "--warn", "rust-2018-idioms",
    "--warn", "clippy::pedantic",
    "--allow", "clippy::missing_errors_doc",
]

[jobs.format]
command = ["cargo", "fmt"]
need_stdout = true
on_success = "back"

[jobs.test]
command = ["cargo", "test"]
need_stdout = true

[jobs.fix]
command = ["cargo", "fix"]
need_stdout = true
on_success = "back"

[jobs.doc]
command = ["cargo", "doc", "--all-features"]

[jobs.doc-open]
command = ["cargo", "doc", "--all-features", "--open"]
on_success = "back" # so that we don't open the browser at each change

[jobs.run]
command = ["cargo", "run"]
need_stdout = true
allow_warnings = true
background = false

[jobs.ex]
command = ["cargo", "run", "--example"]
need_stdout = true
allow_warnings = true


# [export]
# enabled = false
# path = ".bacon-locations"
# line_format = "{kind} {path}:{line}:{column} {message}"
