[metadata]
title = "Workspace menu"
sort_method = "manual"

[[entry]]
description = "Show workspace info"
execute = "spacemux --notification show"
icon = "dialog-information"

[[entry]]
description = "Toggle monitor lock"
execute = "spacemux monitor toggle-lock"
icon = "object-locked"

[[entry]]
description = "Toggle special workspace"
execute = "spacemux special toggle"
icon = "window-new"

[[entry]]
description = "Move to special workspace"
execute = "spacemux special move"
icon = "go-jump"

[[entry]]
description = "Rotate focused cell"
execute = "spacemux cell rotate"
icon = "object-rotate-right"

[[entry]]
description = "Gather external windows"
execute = "spacemux window gather"
icon = "edit-select-all"

[[entry]]
description = "Gather all windows"
execute = "spacemux window gather --all"
icon = "mail-receive"

[[entry]]
description = "Close workspace windows"
execute = "workspace-close"
icon = "window-close"

[[entry]]
description = "Close cell windows"
execute = "workspace-close --visible"
icon = "edit-clear-all"

[[entry]]
description = "Close cell + special windows"
execute = "workspace-close --visible --special"
icon = "edit-delete"
