#! /bin/bash
set -e

SOURCE_DIR=$(realpath $(dirname $0))
ICONS_SOURCE_DIR=$SOURCE_DIR/icons/
ICONS_TAGRET_DIR=/usr/share/icons/dmd/

sudo rm -r $ICONS_TAGRET_DIR
sudo mkdir -p $ICONS_TAGRET_DIR
sudo cp -rt $ICONS_TAGRET_DIR $ICONS_SOURCE_DIR/*
