#! /bin/bash
set -e

SOURCE_DIR=$(realpath $(dirname $0))
SCRIPTS_DIR=$SOURCE_DIR/bin/

STAGING_DIR=/tmp/iukbtw_install_staging
INSTALL_DIR=/usr/bin/iukbtw

progress () { printf "\e[32m$1\e[0m\n" ; }
info () { printf "\e[36m$1\e[0m\n" ; }
notice () { printf "\e[35m$1\e[0m\n" ; }

sudo -v

[[ -d $STAGING_DIR ]] || mkdir --parents $STAGING_DIR

progress "=> Staging..."
cp -rt $STAGING_DIR $SCRIPTS_DIR/*
# remove suffixes in staging
find $STAGING_DIR -type f -name "*.*" -execdir bash -c 'mv "$0" "${0%.*}"' {} \;

progress "=> Installing..."
sudo rm -rf $INSTALL_DIR
sudo install --owner root -Dm 755 -t $INSTALL_DIR $STAGING_DIR/*

progress "=> Cleaning up..."
rm -rf $STAGING_DIR

progress "=> Installed iukbtw."
echo -n "Scripts installed to: "; info "$INSTALL_DIR"
[[ $PATH = *${INSTALL_DIR}* ]] || notice "Be sure to add ${INSTALL_DIR} to PATH."
