#! /bin/bash
set -e

SOURCE_DIR=$(realpath $(dirname $0))

progress () { printf "\e[32m$1\e[0m\n" ; }
warn () { printf "\e[1;38;2;255;96;0m$1\e[0m\n" ; }

sudo -v

progress "=> Installing root environment..."
rootenv='# Add paths to installed binaries and crates via dmd
export PATH="${PATH}:/bin/dmd:/bin/dmd_cargo_crates/bin"
'
printf "$rootenv" | sudo tee /etc/profile.d/dmd.sh
