#! /bin/bash
set -e

SOURCE_DIR=$(realpath $(dirname $0))
CARGO_DEPS_FILE=$SOURCE_DIR/dependencies/cargo.txt
INSTALL_DIR=/bin/dmd_cargo_crates
BIN_DIR=$INSTALL_DIR/bin

notice () { printf "\e[35m$1\e[0m\n" ; }

sudo -v

sudo mkdir --parents $INSTALL_DIR
sudo chown --recursive $USER $INSTALL_DIR
for crate_name in $(cat $CARGO_DEPS_FILE); do
    cargo install --root $INSTALL_DIR $crate_name
done
sudo chown --recursive 0 $INSTALL_DIR
