# For details see: https://platform.openai.com/docs/api-reference/chat

[[models]]
id = "gpt-5"
name = "GPT-5"
max_completion_tokens = 128000
temperature = 1.0
top_p = 1.0
frequency_penalty = 0.0
presence_penalty = 0.0

[[models]]
id = "gpt-5-mini"
name = "GPT-5 mini"
max_completion_tokens = 128000
temperature = 1.0
top_p = 1.0
frequency_penalty = 0.0
presence_penalty = 0.0

[[models]]
id = "gpt-5-nano"
name = "GPT-5 nano"
max_completion_tokens = 128000
temperature = 1.0
top_p = 1.0
frequency_penalty = 0.0
presence_penalty = 0.0

[[models]]
id = "gpt-4.1"
name = "GPT-4.1"
max_completion_tokens = 32768
temperature = 1.0
top_p = 1.0
frequency_penalty = 0.0
presence_penalty = 0.0

[[models]]
id = "o1"
name = "o1"
max_completion_tokens = 65536
temperature = 1.0
top_p = 1.0
frequency_penalty = 0.0
presence_penalty = 0.0

[[models]]
id = "o3-mini"
name = "o3-mini"
max_completion_tokens = 65536
temperature = 1.0
top_p = 1.0
frequency_penalty = 0.0
presence_penalty = 0.0

[[models]]
id = "gpt-4o"
name = "GPT-4o"
max_completion_tokens = 16384
temperature = 1.0
top_p = 1.0
frequency_penalty = 0.0
presence_penalty = 0.0

[[models]]
id = "gpt-4o-mini"
name = "GPT-4o mini"
max_completion_tokens = 16384
temperature = 1.0
top_p = 1.0
frequency_penalty = 0.0
presence_penalty = 0.0
