gui:
  sidePanelWidth: 0.3
  mouseEvents: false
  showFileTree: false
  showBottomLine: false
  nerdFontsVersion: '3'
  showDivergenceFromBaseBranch: arrowAndNumber
  skipDiscardChangeWarning: true
  # expandFocusedSidePanel: true
  # expandedSidePanelWeight: 2
  showFileIcons: true
  statusPanelView: allBranchesLog
  showBranchCommitHash: true
  commandLogSize: 4

  theme:
    activeBorderColor:
      - '#00ffbb'
      - bold
    inactiveBorderColor:
      - white
    inactiveViewSelectedLineBgColor:
      - underline
    searchingActiveBorderColor:
      - cyan
      - bold
    optionsTextColor:
      - blue
    selectedLineBgColor:
      - '#330099'
      - underline
    cherryPickedCommitBgColor:
      - cyan
    cherryPickedCommitFgColor:
      - blue
    unstagedChangesColor:
      - red
    defaultFgColor:
      - default

git:
  autoFetch: false
  parseEmoji: true

  log:
    showGraph: 'always'
    # showWholeGraph: true

disableStartupPopups: true

confirmOnQuit: true

notARepository: skip

customCommands:
  - key: '<c-u>'
    context: 'global'
    command: 'git reset --mixed HEAD^'
    description: 'Uncommit'
  - key: '<c-f>'
    context: 'global'
    command: 'git fetch --all --prune'
    description: 'Fetch and prune'
    loadingText: 'Fetching and pruning...'
