
gui:
  sidePanelWidth: 0.3
  mouseEvents: false
  showFileTree: false
  showBottomLine: false
  nerdFontsVersion: '3'

  log:
    showGraph: 'always'
    showWholeGraph: true

git:
  autoFetch: false
  parseEmoji: true

disableStartupPopups: true
