# hostname = "custom_hostname"

[directories]
# Directories are relative to home directory unless path is absolute
source = ".dmd/home/"
dry_run = "/tmp/homux.dry_run"

[matchpick]
max_file_size = 1_000_000
start_pattern = "~>>>" #NOMATCHPICK#
end_pattern = "~<<<" #NOMATCHPICK#
ignore_pattern = "#NOMATCHPICK#"

[variable_ignore]
line_pattern = "#NOHOMUXVARIABLE#"
files = [
    ".config/homux/config.toml",
]

[variables]
HOMUX_VARIABLE_MONITOR_HOME = "Dell Inc. DELL SE2219H DC464X2"
