# See also: https://wiki.archlinux.org/title/Bash/Prompt_customization
#           

style = "Double"

[text]
user = "\\u"
host = "\\H"
loc = "\\w"
prompt = " "
icon_ok = ""
icon_err = " $?"
at = "@"
sleft = "❰"
sright = "❱"

[fg]
user = "AA77FF"
host = "CC55FF"
loc = "FFCC00"
prompt = "00FF00"
icon_ok = "8899FF"
icon_err = "FF7777"
at = "777777"
sleft = "FF33CC"
sright = "FF33CC"

[command]
fg = "339933"

[ps0] # After each command, before any output
text = ""
color = "FFFFFF"
[ps2] # Multiline prompt
text = " "
color = "FF8800"
[ps4] # Levels of indirection (bash debugging)
text = "↳"
color = "55FFCC"

