[urgency_low]
    background = "#000022cc"
    foreground = "#5555ffff"
    frame_color = "#0000ffff"
    timeout = 20
    default_icon = /usr/share/icons/dmd/tux.svg

[urgency_normal]
    background = "#002200cc"
    foreground = "#55ff55ff"
    frame_color = "#00ff00ff"
    timeout = 120
    default_icon = /usr/share/icons/dmd/arch.svg

[urgency_critical]
    background = "#220000cc"
    foreground = "#ff3333ff"
    frame_color = "#ff0000ff"
    timeout = 0
    default_icon = /usr/share/icons/dmd/error.svg
