[global]
    # ~>>>
    monitor = 0
    # ~>>> home
    monitor = 1
    # ~<<<
    follow = none  # mouse | keyboard | none

    origin = top-right  # center | top-left | bottom-right
    offset = 50x50
