server_endpoint = "/run/user/1000/clipcat/grpc.sock"
finder = "fuzzel"
preview_length = 90
grpc_max_message_size = 8388608

[fuzzel]
# line_length = 100
menu_length = 100
menu_prompt = "Clipcat> "
extra_arguments = []
show_source_prefix = false
