rows = 3
columns = 4
display_priorities = [
~>>>
    "DP-1",
    "DP-2",
    "DP-3",
    "HDMI-1",
    "HDMI-2",
    "HDMI-3",
    "eDP-1",
~>>> zen
    "eDP-1",
    "DP-1",
    "DP-2",
    "DP-3",
    "HDMI-1",
    "HDMI-2",
    "HDMI-3",
~<<<
]
notification_timeout = 2000
