hl.on("hyprland.start", function()
    hl.exec_cmd("waybar")
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("hyprsunset")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("kmdrun")
    hl.exec_cmd("ydotoold --socket-own=\"$(id -u):$(id -g)\"")
    hl.exec_cmd("touchpadtoggle --off")
    hl.exec_cmd("clipcatd")
    hl.exec_cmd("monitor-watchdog")
    hl.exec_cmd("spacemux cell focus 1.1")
    hl.exec_cmd("alacritty")
end)
