argument = [
    { name = "dir" }
]
#>> END OF ARGUMENTS



# Lazygit
[[command]]
command = [
    "alacritty", "--working-directory", "$dir$",
    "--command", "bash", "-c", "lazygit",
]
focus_window = true
pause_seconds = 0.25
[[command]]
command = ["spacemux", "special", "move"]
pause_seconds = 0.25


# Left terminals
[[command]]
command = ["alacritty", "--working-directory", "$dir$"]
# ~>>>
monitor = "eDP-1"
# ~>>> home
monitor = "desc:HOMUX_VARIABLE_MONITOR_HOME_LEFT"
# ~<<<
focus_window = true
[[command]]
command = ["alacritty", "--working-directory", "$dir$"]
# ~>>>
monitor = "eDP-1"
# ~>>> home
monitor = "desc:HOMUX_VARIABLE_MONITOR_HOME_LEFT"
# ~<<<
focus_window = true
[[command]]
command = ["hyprctl", "dispatch", "hl.dsp.window.move({ direction = 'l' })"]
pause_seconds = 0.1



# Main Terminal
[[command]]
command = ["alacritty", "--working-directory", "$dir$"]
# ~>>>
monitor = "eDP-1"
# ~>>> home
monitor = "desc:HOMUX_VARIABLE_MONITOR_HOME_LEFT"
# ~<<<
focus_window = true

# Lite-xl
[[command]]
command = ["lite-xl", "$dir$"]
# ~>>>
monitor = "eDP-1"
# ~>>> home
monitor = "desc:HOMUX_VARIABLE_MONITOR_HOME_RIGHT"
# ~<<<
focus_window = true



# Right terminals
[[command]]
command = ["alacritty", "--working-directory", "$dir$"]
# ~>>>
monitor = "eDP-1"
# ~>>> home
monitor = "desc:HOMUX_VARIABLE_MONITOR_HOME_RIGHT"
# ~<<<
focus_window = true
[[command]]
command = ["alacritty", "--working-directory", "$dir$"]
# ~>>>
monitor = "eDP-1"
# ~>>> home
monitor = "desc:HOMUX_VARIABLE_MONITOR_HOME_RIGHT"
# ~<<<
focus_window = true
[[command]]
command = ["hyprctl", "dispatch", "hl.dsp.window.move({ direction = 'l' })"]
pause_seconds = 0.1


# Extra terminals
[[command]]
command = ["alacritty", "--working-directory", "$dir$"]
# ~>>>
monitor = "eDP-1"
# ~>>> home
monitor = "desc:HOMUX_VARIABLE_MONITOR_HOME_RIGHT"
# ~<<<
focus_window = true

[[command]]
command = ["alacritty", "--working-directory", "$dir$"]
# ~>>>
monitor = "eDP-1"
# ~>>> home
monitor = "desc:HOMUX_VARIABLE_MONITOR_HOME_RIGHT"
# ~<<<
focus_window = true
pause_seconds = 0.1


# Focus
[[command]]
command = ["hyprctl", "dispatch", "hl.dsp.focus({ direction = 'l' })"]
[[command]]
command = ["hyprctl", "dispatch", "hl.dsp.focus({ direction = 'l' })"]
[[command]]
command = ["hyprctl", "dispatch", "hl.dsp.focus({ direction = 'l' })"]
[[command]]
command = ["hyprctl", "dispatch", "hl.dsp.focus({ direction = 'l' })"]
