argument = [
    { name = "dir" }
]
#>> END OF ARGUMENTS



# Lazygit
[[command]]
command = [
    "alacritty", "--working-directory", "$dir$",
    "--command", "bash", "-c", "lazygit",
]
focus_window = true
pause_seconds = 0.25
[[command]]
command = ["spacemux", "special", "move"]
pause_seconds = 0.25



# Lite-xl
[[command]]
command = ["lite-xl", "$dir$"]
# ~>>>
monitor = "desc:HOMUX_VARIABLE_MONITOR_OFFICE_RIGHT"
# ~>>> home
monitor = "desc:HOMUX_VARIABLE_MONITOR_HOME_RIGHT"
# ~>>> road
monitor = "eDP-1"
~<<<
focus_window = true
pause_seconds = 0.25
[[command]]
command = ["hyprctl", "dispatch", "hl.dsp.layout('colresize 0.5')"]

# Main Terminal
[[command]]
command = ["alacritty", "--working-directory", "$dir$"]
# ~>>>
monitor = "desc:HOMUX_VARIABLE_MONITOR_OFFICE_RIGHT"
# ~>>> home
monitor = "desc:HOMUX_VARIABLE_MONITOR_HOME_RIGHT"
# ~>>> road
monitor = "eDP-1"
~<<<
focus_window = true
pause_seconds = 0.25
[[command]]
command = ["hyprctl", "dispatch", "hl.dsp.layout('colresize 0.5')"]



# Support terminals
[[command]]
command = ["alacritty", "--working-directory", "$dir$"]
# ~>>>
monitor = "desc:HOMUX_VARIABLE_MONITOR_OFFICE_RIGHT"
# ~>>> home
monitor = "desc:HOMUX_VARIABLE_MONITOR_HOME_RIGHT"
# ~>>> road
monitor = "eDP-1"
~<<<
focus_window = true

[[command]]
command = ["alacritty", "--working-directory", "$dir$"]
# ~>>>
monitor = "desc:HOMUX_VARIABLE_MONITOR_OFFICE_RIGHT"
# ~>>> home
monitor = "desc:HOMUX_VARIABLE_MONITOR_HOME_RIGHT"
# ~>>> road
monitor = "eDP-1"
~<<<
focus_window = true
pause_seconds = 0.25
[[command]]
command = ["hyprctl", "dispatch", "hl.dsp.window.move({ direction = 'l' })"]
pause_seconds = 0.1

# ~>>>
# ~>>> home
[[command]]
command = ["hyprctl", "dispatch", "hl.dsp.focus({ direction = 'l' })"]
[[command]]
command = ["hyprctl", "dispatch", "hl.dsp.focus({ direction = 'l' })"]
pause_seconds = 0.1
~<<<



# Extra terminals
[[command]]
command = ["alacritty", "--working-directory", "$dir$"]
# ~>>>
monitor = "desc:HOMUX_VARIABLE_MONITOR_OFFICE_LEFT"
# ~>>> home
monitor = "desc:HOMUX_VARIABLE_MONITOR_HOME_LEFT"
# ~>>> road
monitor = "eDP-1"
~<<<
focus_window = true
pause_seconds = 0.25
[[command]]
command = ["hyprctl", "dispatch", "hl.dsp.layout('colresize 0.333')"]
pause_seconds = 0.25

[[command]]
command = ["alacritty", "--working-directory", "$dir$"]
# ~>>>
monitor = "desc:HOMUX_VARIABLE_MONITOR_OFFICE_LEFT"
# ~>>> home
monitor = "desc:HOMUX_VARIABLE_MONITOR_HOME_LEFT"
# ~>>> road
monitor = "eDP-1"
~<<<
focus_window = true
pause_seconds = 0.25
[[command]]
command = ["hyprctl", "dispatch", "hl.dsp.layout('colresize 0.667')"]
pause_seconds = 0.25

[[command]]
command = ["alacritty", "--working-directory", "$dir$"]
# ~>>>
monitor = "desc:HOMUX_VARIABLE_MONITOR_OFFICE_LEFT"
# ~>>> home
monitor = "desc:HOMUX_VARIABLE_MONITOR_HOME_LEFT"
# ~>>> road
monitor = "eDP-1"
~<<<
focus_window = true
pause_seconds = 0.25

[[command]]
command = ["alacritty", "--working-directory", "$dir$"]
# ~>>>
monitor = "desc:HOMUX_VARIABLE_MONITOR_OFFICE_LEFT"
# ~>>> home
monitor = "desc:HOMUX_VARIABLE_MONITOR_HOME_LEFT"
# ~>>> road
monitor = "eDP-1"
# ~<<<
focus_window = true
pause_seconds = 0.25


# ~>>>
[[command]]
command = ["hyprctl", "dispatch", "hl.dsp.focus({ direction = 'l' })"]
[[command]]
command = ["hyprctl", "dispatch", "hl.dsp.focus({ direction = 'l' })"]
[[command]]
command = ["hyprctl", "dispatch", "hl.dsp.focus({ direction = 'l' })"]
[[command]]
command = ["hyprctl", "dispatch", "hl.dsp.focus({ direction = 'l' })"]
[[command]]
command = ["hyprctl", "dispatch", "hl.dsp.focus({ direction = 'l' })"]
[[command]]
command = ["hyprctl", "dispatch", "hl.dsp.focus({ direction = 'l' })"]
# ~>>> home
[[command]]
command = ["hyprctl", "dispatch", "hl.dsp.focus({ direction = 'r' })"]
[[command]]
command = ["hyprctl", "dispatch", "hl.dsp.focus({ direction = 'r' })"]
[[command]]
command = ["hyprctl", "dispatch", "hl.dsp.focus({ direction = 'r' })"]
[[command]]
command = ["hyprctl", "dispatch", "hl.dsp.focus({ direction = 'r' })"]
~<<<
