[[argument]]
name = "dir-path"

#>> END OF ARGUMENTS

[[command]]
command = [
    "alacritty", "--working-directory", "$dir-path$",
    "--command", "bash", "-c", "lazygit",
]
focus_window = true

[[command]]
command = ["spacemux", "special", "move"]
pause_seconds = 0.25

[[command]]
command = ["alacritty", "--working-directory", "$dir-path$"]
focus_window = true
monitor = "eDP-1"

[[command]]
command = ["alacritty", "--working-directory", "$dir-path$"]
focus_window = true
monitor = "eDP-1"

[[command]]
command = ["lite-xl", "$dir-path$"]
focus_window = true
monitor = "eDP-1"

[[command]]
command = ["hyprctl", "--batch", "dispatch movefocus u;dispatch movewindow d;dispatch movewindow l;dispatch movefocus r"]
