argument = [
    { name = "dir" }
]

#>> END OF ARGUMENTS

[[command]]
command = [
    "alacritty", "--working-directory", "$dir$",
    "--command", "bash", "-c", "lazygit",
]
focus_window = true

[[command]]
command = ["spacemux", "special", "move"]
pause_seconds = 0.25

[[command]]
command = ["alacritty", "--working-directory", "$dir$"]
focus_window = true
monitor = "eDP-1"

[[command]]
command = ["alacritty", "--working-directory", "$dir$"]
focus_window = true
monitor = "eDP-1"

[[command]]
command = ["cursor", "$dir$"]
focus_window = true
monitor = "eDP-1"

[[command]]
command = ["hyprctl", "dispatch layoutmsg swapwithmaster master ignoremaster"]
