general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = pidof hyprlock || hyprlock
}

listener {
    timeout = 240
    on-timeout = setmonbrightness --set 5
    on-resume = setmonbrightness --set 10
}

listener {
    timeout = 300
    on-timeout = pidof hyprlock || hyprlock
}

listener {
    timeout = 300
    on-timeout = notify-send -u low "Idle..."
}

# listener {
#     timeout = 600
#     on-timeout = setmonbrightness --set 1
# }

# listener {
#     timeout = 720
#     on-timeout = systemctl suspend
# }
