max-gamma = 200

profile {
    time = 5:00
    identity = true
}

profile {
    time = 21:00
    temperature = 4000
    # gamma = 1
}

profile {
    time = 22:30
    temperature = 2800
    # gamma = 0.8
}
