
[ui]
cols = 1
rows = 1


[fonts]
# code.size = 22


[editor]
cursor_scroll_offset = 20


[linter]
ignore = "E203,D,"


[project]
file_types = [
    "py",
    "hs",
    "txt",
    "md",
    "toml",
    "json",
    "yml",
    "sh",
    "log",
    "jinja2",
    "html",
    "css",
    "xml",
    "",  # For files without extensions (like .gitignore)
]
ignore_names = [
    ".git/",
    "venv/",
    "build/",
    "__pycache__/",
    ".pytest_cache",
    ".hypothesis",
    ".egg-info",
    ".idea",
    "assets/",
    "docs/",
]
bookmarks = [
    "~/;Home",
    "~/prog/;Prog",
    "~/temp/;Temp",
    "~/prog/testing/;Testing",
    "~/.scripts/;Scripts",
    "~/.gitignore;home gitignore",
    "~/.bashrc;bashrc config",
    "~/.profile;bash profile",
    "~/.config/;Local config",
    "~/.config/kmonad/template.kbd;kmonad config template",
    "~/.config/i3/config;i3 config",
    "~/.config/lazygit/config.yml;lazygit config",
    "~/.alacritty.yml;alacritty config",
    "~/.gitconfig;git config",
    "~/.local/share/positron/;Positron config",
]


[path_prefixes]
custom = [
    "/run/media/wiw/WHITE/ninja/prog/;$PROG",
    "/run/media/wiw/WHITE/ninja/;$NINJA",
    "~/prog/;$PROG",
]
