[colors]
draw_bold_text_with_bright_colors = false

~>>>
[colors.normal]
black =   "0x000000"
white =   "0x999999"
red =     "0x9D0000"
yellow =  "0x767600"
green =   "0x178900"
blue =    "0x2E2EFF"
magenta = "0x9D009D"
cyan =    "0x008989"
[colors.bright]
black =   "0x303030"
white =   "0xFFFFFF"
red =     "0xFF0000"
yellow =  "0xFFFF00"
green =   "0x00FF00"
blue =    "0x4040FF"
magenta = "0xFF00FF"
cyan =    "0x00FFFF"
~>>> test-pastel
[colors.normal]
black =   "0x000000"
white =   "0xffffff"
red =     "0xEFA6A2"
yellow =  "0xA69460"
green =   "0x80C990"
blue =    "0xA3B8EF"
magenta = "0xE6A3DC"
cyan =    "0x50CACD"
[colors.bright]
black =   "0x454545"
white =   "0xC0C0C0"
red =     "0xE0AF85"
yellow =  "0xC8C874"
green =   "0x5ACCAF"
blue =    "0xCCACED"
magenta = "0xF2A1C2"
cyan =    "0x74C3E4"
~<<<

[colors.primary]
background = "0x111111"
foreground = "0xffffff"

[cursor]
blink_interval = 350

[cursor.style]
blinking = "On"
shape = "Beam"

[font]
# ~>>>
size = 10
# ~>>> lemnos
size = 7
# ~<<<

[font.bold]
family = "FiraCode Nerd Font"
[font.bold_italic]
family = "FiraCode Nerd Font"
[font.italic]
family = "FiraCode Nerd Font"
[font.normal]
family = "FiraCode Nerd Font"

[window]
dynamic_title = true
startup_mode = "Windowed"

[window.padding]
x = 2
y = 2
